# Generated by Django 6.1.1 on 2026-09-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('hospitality', 'Hospitality Manpower'), ('hospital', 'Hospital Manpower'), ('industrial', 'Industrial Manpower'), ('facility_management', 'Facility Management'), ('cleaning', 'Cleaning Services'), ('garden_landscape', 'Garden & Landscape Services'), ('corporate', 'Corporate Manpower'), ('commercial', 'Commercial Support Services')], max_length=30)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('long_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier, e.g. lucide icon name', max_length=100)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
