# Generated by Django 6.1.1 on 2026-09-20 08:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9\\s-]{7,15}$')])),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9\\s-]{7,15}$')])),
                ('industry', models.CharField(choices=[('hotel_hospitality', 'Hotel / Hospitality'), ('hospital_healthcare', 'Hospital / Healthcare'), ('industrial', 'Industrial'), ('manufacturing', 'Manufacturing'), ('corporate', 'Corporate'), ('commercial', 'Commercial'), ('resort', 'Resort'), ('residency', 'Residency'), ('other', 'Other')], max_length=30)),
                ('service_name_freeform', models.CharField(blank=True, help_text='Used if the requested service is not in the catalog', max_length=200)),
                ('manpower_required', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('location_freeform', models.CharField(blank=True, max_length=200)),
                ('preferred_start_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_discussion', 'In Discussion'), ('proposal_sent', 'Proposal Sent'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='locations.location')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='services.service')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
