# Generated by Django 6.1.1 on 2026-09-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='PHOENIX BIRDS', max_length=255)),
                ('tagline', models.CharField(blank=True, default='Professional Manpower & Facility Support Solutions', max_length=255)),
                ('phone_primary', models.CharField(blank=True, max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Include country code, e.g. 91XXXXXXXXXX', max_length=20)),
                ('email_primary', models.EmailField(blank=True, max_length=254)),
                ('email_enquiries', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, default='Madurai', max_length=100)),
                ('state', models.CharField(blank=True, default='Tamil Nadu', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('google_maps_url', models.URLField(blank=True)),
                ('office_hours', models.CharField(blank=True, default='Mon - Sat: 9:00 AM - 6:00 PM', max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
